name: Rust

on: 
  push:
  
  schedule:
    - cron: "0 15 * * 1" # Run at 7 AM PST every Monday

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
